# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diagnosis.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_add_diag(object):
    def setupUi(self, Dialog_add_diag):
        Dialog_add_diag.setObjectName("Dialog_add_diag")
        Dialog_add_diag.resize(582, 60)
        self.dateEdit_add_diag = QtWidgets.QDateEdit(Dialog_add_diag)
        self.dateEdit_add_diag.setGeometry(QtCore.QRect(0, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateEdit_add_diag.setFont(font)
        self.dateEdit_add_diag.setObjectName("dateEdit_add_diag")
        self.apart_add_diag = QtWidgets.QLineEdit(Dialog_add_diag)
        self.apart_add_diag.setGeometry(QtCore.QRect(120, 20, 41, 21))
        self.apart_add_diag.setObjectName("apart_add_diag")
        self.patient_add_diag = QtWidgets.QLineEdit(Dialog_add_diag)
        self.patient_add_diag.setGeometry(QtCore.QRect(160, 20, 121, 21))
        self.patient_add_diag.setObjectName("patient_add_diag")
        self.diagnosis_add_diag = QtWidgets.QLineEdit(Dialog_add_diag)
        self.diagnosis_add_diag.setGeometry(QtCore.QRect(280, 20, 301, 21))
        self.diagnosis_add_diag.setObjectName("diagnosis_add_diag")
        self.label_10 = QtWidgets.QLabel(Dialog_add_diag)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setStyleSheet("")
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog_add_diag)
        self.label_11.setGeometry(QtCore.QRect(130, 0, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog_add_diag)
        self.label_12.setGeometry(QtCore.QRect(170, 0, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setTextFormat(QtCore.Qt.PlainText)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Dialog_add_diag)
        self.label_13.setGeometry(QtCore.QRect(290, 0, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setTextFormat(QtCore.Qt.PlainText)
        self.label_13.setObjectName("label_13")
        self.add_to_table_Button = QtWidgets.QPushButton(Dialog_add_diag)
        self.add_to_table_Button.setGeometry(QtCore.QRect(510, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_to_table_Button.setFont(font)
        self.add_to_table_Button.setObjectName("add_to_table_Button")

        self.retranslateUi(Dialog_add_diag)
        QtCore.QMetaObject.connectSlotsByName(Dialog_add_diag)

    def retranslateUi(self, Dialog_add_diag):
        _translate = QtCore.QCoreApplication.translate
        Dialog_add_diag.setWindowTitle(_translate("Dialog_add_diag", "Dialog"))
        self.label_10.setText(_translate("Dialog_add_diag", "Дата"))
        self.label_11.setText(_translate("Dialog_add_diag", "кв."))
        self.label_12.setText(_translate("Dialog_add_diag", "Пацієнт"))
        self.label_13.setText(_translate("Dialog_add_diag", "Діагноз"))
        self.add_to_table_Button.setText(_translate("Dialog_add_diag", "додати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_add_diag = QtWidgets.QDialog()
    ui = Ui_Dialog_add_diag()
    ui.setupUi(Dialog_add_diag)
    Dialog_add_diag.show()
    sys.exit(app.exec_())
