# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'photo_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PhotoList(object):
    def setupUi(self, PhotoList):
        PhotoList.setObjectName("PhotoList")
        PhotoList.resize(488, 678)
        self.gridLayout = QtWidgets.QGridLayout(PhotoList)
        self.gridLayout.setObjectName("gridLayout")
        self.loadButton = QtWidgets.QPushButton(PhotoList)
        self.loadButton.setObjectName("loadButton")
        self.gridLayout.addWidget(self.loadButton, 1, 0, 1, 1)
        self.updateButton = QtWidgets.QPushButton(PhotoList)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout.addWidget(self.updateButton, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(PhotoList)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 629))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 2)

        self.retranslateUi(PhotoList)
        QtCore.QMetaObject.connectSlotsByName(PhotoList)

    def retranslateUi(self, PhotoList):
        _translate = QtCore.QCoreApplication.translate
        PhotoList.setWindowTitle(_translate("PhotoList", "Dialog"))
        self.loadButton.setText(_translate("PhotoList", "Добавить фото"))
        self.updateButton.setText(_translate("PhotoList", "Оновити"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PhotoList = QtWidgets.QDialog()
    ui = Ui_PhotoList()
    ui.setupUi(PhotoList)
    PhotoList.show()
    sys.exit(app.exec_())
