# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_files\address_lists.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Address_listsWindow(object):
    def setupUi(self, Address_listsWindow):
        Address_listsWindow.setObjectName("Address_listsWindow")
        Address_listsWindow.resize(276, 820)
        self.centralwidget = QtWidgets.QWidget(Address_listsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_change_table = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_change_table.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_change_table.setFont(font)
        self.comboBox_change_table.setObjectName("comboBox_change_table")
        self.gridLayout.addWidget(self.comboBox_change_table, 0, 0, 1, 2)
        self.address_lookup = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_lookup.sizePolicy().hasHeightForWidth())
        self.address_lookup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.address_lookup.setFont(font)
        self.address_lookup.setObjectName("address_lookup")
        self.gridLayout.addWidget(self.address_lookup, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        Address_listsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Address_listsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 276, 21))
        self.menubar.setObjectName("menubar")
        Address_listsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Address_listsWindow)
        self.statusbar.setObjectName("statusbar")
        Address_listsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Address_listsWindow)
        QtCore.QMetaObject.connectSlotsByName(Address_listsWindow)

    def retranslateUi(self, Address_listsWindow):
        _translate = QtCore.QCoreApplication.translate
        Address_listsWindow.setWindowTitle(_translate("Address_listsWindow", "MainWindow"))
        self.saveButton.setText(_translate("Address_listsWindow", "Зберегти"))
        self.label.setText(_translate("Address_listsWindow", "Пошук"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Address_listsWindow = QtWidgets.QMainWindow()
    ui = Ui_Address_listsWindow()
    ui.setupUi(Address_listsWindow)
    Address_listsWindow.show()
    sys.exit(app.exec_())
